### ISSUE TITLE
chrome blocked

### ISSUE THREAD

**Issue by mithuncoder** [Fadi002/de4py#11]
![screenshot](https://github.com/Fadi002/de4py/assets/96990204/614224ad-b2fd-4c49-a1a5-556e0d7ca694)

When I Download the zip file, Chrome Will blocked the download and mark as Malicious..Why?

**Comment by AdvDebug** [comment]
de4py have some modules that modify the program behavior using hooking to (for example) tell you what the program is doing and even dump socket content and it's a toolkit that contains a lot of code that AVs may find malicious, because this program is a RE toolkit it can obviously be marked as malicious while it's not because of the modules in it and the injection capabilities it have that should be used in order for it to be able to inject itself into the python program and monitor it's behavior.
